---
title: "BlackFridaySale Prediction"
author: "Parthasarathi Samantaray"
date: "March 25, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

## loading libraries
library(dummies)
library(plyr)
library(tidyverse)
library(gbm)

```


```{r}

## loading data
train <- read.csv("train.csv", stringsAsFactors=F)
test <- read.csv("test.csv", stringsAsFactors=F)


```


```{r}
train %>% summary()


```


```{r}
train %>% head(5)
```



```{r}
#Gender Break up 
train$Gender %>% table()
#Age Break up
train$Age %>% table()

train$Occupation %>% table()

train$City_Category %>% table()

train$Stay_In_Current_City_Years %>% table()

train$Marital_Status %>% table()

train$Product_Category_1 %>% table()


train$Product_Category_2 %>% table()


train$Product_Category_3 %>% table()



```

```{r}
## cleaning data

# removing categories 19 and 20
X_train <- subset(train, !Product_Category_1 %in% c(19,20))
X_test <- test

# onehot-encoding city variable
X_train <- dummy.data.frame(X_train, names=c("City_Category"), sep="_")
X_test <- dummy.data.frame(X_test, names=c("City_Category"), sep="_")

# converting age variable to numeric
X_train$Age[X_train$Age == "0-17"] <- "15"
X_train$Age[X_train$Age == "18-25"] <- "21"
X_train$Age[X_train$Age == "26-35"] <- "30"
X_train$Age[X_train$Age == "36-45"] <- "40"
X_train$Age[X_train$Age == "46-50"] <- "48"
X_train$Age[X_train$Age == "51-55"] <- "53"
X_train$Age[X_train$Age == "55+"] <- "60"

X_test$Age[X_test$Age == "0-17"] <- "15"
X_test$Age[X_test$Age == "18-25"] <- "21"
X_test$Age[X_test$Age == "26-35"] <- "30"
X_test$Age[X_test$Age == "36-45"] <- "40"
X_test$Age[X_test$Age == "46-50"] <- "48"
X_test$Age[X_test$Age == "51-55"] <- "53"
X_test$Age[X_test$Age == "55+"] <- "60"

X_train$Age <- as.integer(X_train$Age)
X_test$Age <- as.integer(X_test$Age)

# converting stay in current city to numeric
X_train$Stay_In_Current_City_Years[X_train$Stay_In_Current_City_Years == "4+"] <- "4"
X_test$Stay_In_Current_City_Years[X_test$Stay_In_Current_City_Years == "4+"] <- "4"

X_train$Stay_In_Current_City_Years <- as.integer(X_train$Stay_In_Current_City_Years)
X_test$Stay_In_Current_City_Years <- as.integer(X_test$Stay_In_Current_City_Years)

# converting gender to binary
X_train$Gender <- ifelse(X_train$Gender == "F", 1, 0)
X_test$Gender <- ifelse(X_test$Gender == "F", 1, 0)

```

```{r}
X_train %>% head(3)

```


```{r}


# feature representing the count of each user
user_count <- ddply(X_train, .(User_ID), nrow)

user_count %>% head()
```

```{r}
names(user_count)[2] <- "User_Count"
X_train <- merge(X_train, user_count, by="User_ID")
X_test <- merge(X_test, user_count, all.x=T, by="User_ID")
```

```{r}
# feature representing the count of each product
product_count <- ddply(X_train, .(Product_ID), nrow)
product_count %>% head()

```



```{r}
names(product_count)[2] <- "Product_Count"
X_train <- merge(X_train, product_count, by="Product_ID")
X_test <- merge(X_test, product_count, all.x=T, by="Product_ID")
X_test$Product_Count[is.na(X_test$Product_Count)] <- 0
```


```{r}

# feature representing the average Purchase of each product
product_mean <- ddply(X_train, .(Product_ID), summarize, Product_Mean=mean(Purchase))
product_mean %>% head()
```

```{r}
X_train <- merge(X_train, product_mean, by="Product_ID")
X_test <- merge(X_test, product_mean, all.x=T, by="Product_ID")
X_test$Product_Mean[is.na(X_test$Product_Mean)] <- mean(X_train$Purchase)

```


```{r}

# feature representing the proportion of times the user purchases the product more than the product's average
X_train$flag_high <- ifelse(X_train$Purchase > X_train$Product_Mean,1,0)
user_high <- ddply(X_train, .(User_ID), summarize, User_High=mean(flag_high))
X_train <- merge(X_train, user_high, by="User_ID")
X_test <- merge(X_test, user_high, by="User_ID")

```

```{r}
X_train %>% head()

```

```{r}
X_test %>% head()
```

```{r}

# subsetting columns for submission
submit <- X_test[,c("User_ID","Product_ID")]

```
```{r}
X_train %>% names()
```



```{r}
# removing irrelevant columns
X_train <- subset(X_train, select=-c(flag_high,Product_ID))

X_test <- subset(X_test, select=-(Product_ID))



```

```{r}
X_train%>% names()
X_test %>% names()
```


```{r}
X_train %>% head(3)
```


```{r}


## gbm with cross validation

# train a GBM model
model <- gbm(formula = Purchase ~ .,
distribution = "gaussian",
data = X_train,
n.trees = 500,
cv.folds = 5)

```


```{r}
# get optimal ntree based on CV error
ntree_opt_cv <- gbm.perf(model, method = "cv")
```

```{r}
# get optimal ntree based on OOB error
ntree_opt_oob <- gbm.perf(model, method = "OOB")
```
```{r}
summary(model)
```

```{r}
test_predgbm<-predict(model,newdata = X_test, type = "response", n.trees = ntree_opt_oob)
```
```{r}
test_predgbm %>% summary()
```

```{r}


# adding predictions
submit$Purchase <- test_predgbm

```
```{r}
submit$Purchase[submit$Purchase < 0] <- 0
```


```{r}

write.csv(submit, "submit.csv", row.names=F)

```

